before_script:
  - apt-get update -qq && apt-get install -y -qq python3

build:
  script:
    - python3 txtmerge.py locations glife.txt
    - ./txt2gam.linux glife.txt glife.qsp
  artifacts:
    paths:
    - glife.qsp